##指定运行环境
#language: java
##指定nodejs版本，可以指定多个
##node_js:
##  - 0.12.5
#
##运行的脚本命令
#script:
#  - gradle check
#  - gradle assemble
#
##指定分支，只有指定的分支提交时才会运行脚本
#branches:
#  only:
#    - master

language: java
jdk:
  - oraclejdk8
script:
  - gradle xiaoyaoji-web:assemble